# Generated by Django 3.0.8 on 2020-07-14 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 12, 59, 23, 831512, tzinfo=utc)),
        ),
    ]
