# Generated by Django 3.0.8 on 2020-07-14 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_auto_20200714_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='person',
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
