# Generated by Django 3.0.8 on 2020-07-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor')], default='I', max_length=2),
        ),
    ]
