# Generated by Django 3.0.8 on 2020-07-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social',
        ),
    ]
