# Generated by Django 3.0.8 on 2020-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
