# Generated by Django 3.0.8 on 2020-07-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200714_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
